### ISSUE TITLE
Readme.md Contradicts Itself

### ISSUE THREAD

**Issue by cybersenshi** [RosieSews/website#10]
Says the site should both be migrated to Netlify and runs on Netlify,

**Comment by gvan12** [comment]
It currently is _not_ hosted by Netlify but that "run's on Netlify" verbiage is a requirement to apply for the opensource treatment. Thanks for pointing it out and we'll resolve it once migrated.

**Comment by cybersenshi** [comment]
Ah. Copy that.
Thanks for the info.

**Comment by gvan12** [comment]
fixed in eec6a14.
