### ISSUE TITLE
Add hosting/SSL cert for www.

### ISSUE THREAD

**Issue by jcooter** [RosieSews/website#8]
It looks like the SSL cert and hosting aren't set up for www.rosiesews.org - and some people are apparently going out of their way to add the www. to their browser.  So, we should probably fix that at some point.

**Comment by gvan12** [comment]
I thought I'd included the www as well. Will check asap (may be a few hours though)

**Comment by jcooter** [comment]
Yeah, we're not linking to it anywhere with the www. so I consider it low priority

**Comment by gvan12** [comment]
resolved on firebase hosting.
